version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    networks:
      - local
    ports:
      - '5433:5433'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - /Users/kroglid/Documents/norad/flood-frontend/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
    environment:
      - FLOOD_FRONTEND_CLIENT_SECRET=secret
      - FLOOD_FRONTEND_CLIENT_ID=web
      - FLOOD_FRONTEND_DOMAIN=localhost:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_PORT=5433
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KC_BOOTSTRAP_ADMIN_USERNAME=keycloak
      - KC_BOOTSTRAP_ADMIN_PASSWORD=keycloak
      - KC_PROXY=edge
      - KC_HOSTNAME=http://localhost:8080
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    ports:
      - 8080:8080
    links:
      - postgres
    networks:
      - local
    depends_on:
      postgres:
        condition: service_healthy

networks:
  local:
    name: local
    driver: bridge
