version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: db
    image: postgres:15.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Henrik123
      POSTGRES_DB: keycloak
    networks:
      - local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.0
    build:
      context: .
      dockerfile: ./docker/keycloak/Dockerfile
    command:
      - start
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=Henrik123
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
    ports:
      - 8080:8080
    networks:
      - local
    depends_on:
      - postgres

networks:
  local:
    name: local
    driver: bridge
