version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: db
    image: postgres:15.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Henrik123
      POSTGRES_DB: keycloak
    networks:
      - local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: ghcr.io/openearthplatforminitiative/flood-frontend-keycloak:latest
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=Henrik123
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - 8080:8080
    networks:
      - local
    depends_on:
      - postgres

networks:
  local:
    name: local
    driver: bridge
