apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flood-frontend
  namespace: flood-frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: flood-frontend
    server: https://kubernetes.default.svc
  project: flood-frontend
  source:
    repoURL: https://github.com/openearthplatforminitiative/flood-frontend
    targetRevision: HEAD
    path: deployment/kubernetes/
  syncPolicy:
    automated:
      prune: true
