apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flood-frontend
  namespace: apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: apps
  source:
    repoURL: https://github.com/openearthplatforminitiative/flood-frontend
    targetRevision: fix/make-rds-instance-delete-properly
    path: deployment/kubernetes/
  syncPolicy:
    automated:
      prune: true
