apiVersion: apps/v1
kind: Deployment
metadata:
  name: flood-frontend
  namespace: apps
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flood-frontend
  template:
    metadata:
      namespace: apps
      labels:
        app: flood-frontend
    spec:
      containers:
        - image: ghcr.io/openearthplatforminitiative/flood-frontend:0.0.1
          name: flood-frontend
          ports:
            - containerPort: 3000
          env:
            - name: VERSION
              value: 0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: flood-frontend
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: flood-frontend
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: flood-frontend
spec:
  http:
    - name: flood-frontend
      match:
        hosts:
          - flood*.openepi.io
      backends:
        - serviceName: flood-frontend
          servicePort: 80
