import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Box } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={lang}>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#90cdf4" />
        <title>FloodSafe</title>
      </head>
      <body
        style={{
          display: 'flex',
          height: '100%',
          width: '100%',
          margin: 0,
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Box
          sx={{
            height: '800px',
            width: '360px',
          }}
        >
          {children}
        </Box>
      </body>
    </html>
  );
}
