name: Continous Integration for flood-frontend Keycloak-image
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'keycloak/**'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build keycloak Docker image
        uses: docker/build-push-action@v5
        with:
          context: keycloak
          push: false
