name: Continous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (migrator)
        uses: docker/build-push-action@v5
        with:
          context: .
          target: migrator
          push: false

      - name: Build Docker Image (runner)
        uses: docker/build-push-action@v5
        with:
          context: .
          target: runner
          push: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check linting
        run: npm run lint
